apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth

spec:
  # two instances of the service
  replicas: 2
  selector:
    matchLabels:
      app: auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: sugar427/auth
          ports:
          # app running on port 5000
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: auth-configmap
            - secretRef:
                name: auth-secret